---
# This Playbook deploys a KairosDB cluster on Amazon EC2

- hosts: tag_kairos_true
  remote_user: ubuntu
  sudo: true
  gather_facts: yes
  vars_files:
  - "group_vars/ubuntu"
  - "group_vars/aws"
  roles:
  - role: ssh
  - role: java
  - role: kairos